Add FCM notification support
Compizfox/Inschrijflijst pull request #3
Opened 2019-04-11 17:24 UTC by TranceAccount

This should make it possible to create notifications for android app users.

2019-04-25 12:33 UTC, Compizfox requested changes

2019-04-25 12:33 UTC, Compizfox commented on app/forms/EventForm.py
> +				# Notification not sent
Dit afhandelen met een foutmelding of zo

2019-04-25 12:33 UTC, Compizfox commented on app/services/FCMService.py
> +        response = messaging.send(message)
```suggestion
        messaging.send(message)
```

2019-04-25 12:33 UTC, Compizfox commented on app/forms/EventForm.py
> +	send_notification = forms.BooleanField(required=False, initial=True, label=_("Stuur notificatie naar app gebruikers"))
Hiervoor Engelse vertaling

2019-05-05 10:21 UTC, TranceAccount commented
> 
> 
> Dit heeft geen zin: je catcht een RunTimeError, en throwt dan weer een nieuwe....

Als het goed is moet het nu wel werken, alleen weet ik niet 100% zeker of de 'pass' statement nodig is na het bericht van django

2019-05-18 09:47 UTC, TranceAccount commented
Ik heb het geprobeerd te testen op de test website, maar er ontstaat blijkbaar een internal server error.

2019-05-27 21:21 UTC, merged